name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker compose build

    - name: Run tests
      run: docker compose run djangoapi python manage.py test
      id: tests

    - name: Deploy to remote Docker host over SSH
      # if: success() && github.ref == 'refs/heads/master'
      uses: appleboy/ssh-action@v0.1.7

      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          git clone https://github.com/${{ github.repository }}.git
          cd $(echo ${{ github.repository }} | cut -d '/' -f 2)
          docker-compose down
          docker-compose up -d