name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker compose build
      id: build

    - name: Run tests
      if: steps.build.outcome == 'success'
      run: docker compose run djangoapi python manage.py test
      id: tests

    - name: Deploy to remote Docker host over SSH
      if: steps.tests.outcome == 'success'
      # uses: appleboy/ssh-action@v0.1.7

      run: docker save djangoapi | ssh -C -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} sudo docker load